# Generated by Django 2.0.5 on 2018-05-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenant',
            name='intervenant_description',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='intervenant_prenom',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
