# Generated by Django 2.0.5 on 2018-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20180509_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenant',
            name='adresse_mail',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='date_naissance',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='intervenant_description',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='intervenant_prenom',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='photo_de_profil',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='table_fichier',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='intervenant_nom',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
